apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.service.name }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: {{ .Values.service.protocol }}

  selector:
    app: {{ .Values.pod.label }}
